# Orchestra system settings

settings:
  # Claude Code session-based timing (5-hour sessions)
  session_duration_hours: 5     # Claude session duration
  final_window_minutes: 15      # Minutes before session end to maximize usage
  
  # Workday mode settings
  workday_max_repos: 3          # Limit repos processed in workday mode
  
  # System settings
  log_level: "INFO"             # DEBUG, INFO, WARNING, ERROR
  claude_code_enabled: true     # Set to false to disable Claude Code calls
  
  # GitHub integration settings
  github_timeout: 30            # Timeout for gh commands in seconds
  
  # Weekend monitoring settings
  weekend_high_priority_only: true  # Only monitor high-priority repos on weekends